errorFile = [
    {
        "code": "1",
        "view_section": "Member",
        "description": "Setup save form valid but not complete and form not valid",
        "swedish": "Det saknas information i något av de obligatoriska fälten.",
    },
    {
        "code": "2",
        "view_section": "Member",
        "description": "Setup save user does not exist",
        "swedish": "Något gick fel när vi försökte ställa in ditt konto. Kontakta supporten för hjälp.",
    },
    {
        "code": "3",
        "view_section": "Member",
        "description": "Company save address does not exist",
        "swedish": "Någonting gick fel vid sparandet av företagsinformationen. Var god kontakta support för assistans.",
    },
    {
        "code": "4",
        "view_section": "Member",
        "description": "Company save form not complete",
        "swedish": "Något i formuläret saknas Var god fyll i hela formuläret.",
    },
    {
        "code": "5",
        "view_section": "Member",
        "description": "Overview access",
        "swedish": "Något gick fel när vi försökte ladda din överblicks sida. Kontakta supporten för assistans.",
    },
    {
        "code": "6",
        "view_section": "Member",
        "description": "MultipleOrderView access",
        "swedish": "Något gick fel när vi försökte ladda dina ordrar. Var god kontakta supporten för assistans.",
    },
    {
        "code": "7",
        "view_section": "Member",
        "description": "single order view access",
        "swedish": "Kan inte hitta denna order. Om detta återupprepas, var god kontakta supporten för assistans.",
    },
    {
        "code": "8",
        "view_section": "Moderator",
        "description": "single freight access",
        "swedish": "Kan inte hitta detta fraktalternativ. Om detta återupprepas, var god kontakta IT supporten för assistans.",
    },
    {
        "code": "9",
        "view_section": "Moderator",
        "description": "single coupon access",
        "swedish": "Kan inte hitta denna kuppong. Om detta återupprepas, var god kontakta IT supporten för assistans.",
    },
    {
        "code": "10",
        "view_section": "Support",
        "description": "Order Item access",
        "swedish": "Kan inte hitta den kopplade varan. Om detta återupprepas, var god kontakta IT supporten för assistans.",
    },
    {
        "code": "11",
        "view_section": "Member",
        "description": "profile access",
        "swedish": "Något gick fel vid laddningen av din profil. Var god kontakta supporten för assistans.",
    },
    {
        "code": "12",
        "view_section": "Member",
        "description": "profile delete address connected to a company",
        "swedish": "Denna adress är kopplad till ditt företag och kan därför inte tas bort. Var god ändra företagets address innan du tar bort denna address.",
    },
    {
        "code": "13",
        "view_section": "Member",
        "description": "profile delete address connected to a subscription",
        "swedish": "Denna adress är kopplad till åtmindstone en av dina prenumerationer. Var god ändra dina prenumerationer innan du tar bort denna address.",
    },
    {
        "code": "14",
        "view_section": "Member",
        "description": "info view access",
        "swedish": "Något gick fel vid laddningen av sidan. Var god kontakta support för assistans.",
    },
    {
        "code": "15",
        "view_section": "Member",
        "description": "info view save",
        "swedish": "Det saknas information i de obligatoriska fälten. Var god fyll i formuläret fullständigt.",
    },
    {
        "code": "16",
        "view_section": "Member",
        "description": "edit address access",
        "swedish": "Något gick fel vid laddningen av denna adress. Om detta fel fortsätter inträffa, var god kontakta supporten för assistans.",
    },
    {
        "code": "17",
        "view_section": "Member",
        "description": "edit address saving",
        "swedish": "Något gick fel vid sparandet av denna adress. Om detta fel fortsätter inträffa, var god kontakta supporten för assistans.",
    },
    {
        "code": "18",
        "view_section": "Member",
        "description": "edit address updating, address doesnt exist",
        "swedish": "Något gick fel vid sparandet av denna adress. Om detta fel fortsätter inträffa, var god kontakta supporten för assistans.",
    },
    {
        "code": "19",
        "view_section": "Member",
        "description": "new address saving",
        "swedish": "Något gick fel vid sparandet av denna adress. Om detta fel fortsätter inträffa, var god kontakta supporten för assistans.",
    },
    {
        "code": "20",
        "view_section": "Member",
        "description": "settings access",
        "swedish": "Något gick fel vid laddningen av dina inställningar. Om detta fel fortsätter inträffa, var god kontakta supporten för assistans.",
    },
    {
        "code": "21",
        "view_section": "Member",
        "description": "multiple subscriptions access",
        "swedish": "Något gick fel vid laddningen av dina prenumerationer. Om detta fel fortsätter inträffa, var god kontakta supporten för assistans.",
    },
    {
        "code": "22",
        "view_section": "Member",
        "description": "multiple subscriptions delete, sub active with no order, this is really bad make sure this flags for IT",
        "swedish": "Prenumerationen borttagen. Denna prenumeration var aktiv utan en kopplad order. Om du fortfarande ser en order under dina ordrar som du tror kommer av denna prenumeration kontakta supporten för assistans.",
    },
    {
        "code": "23",
        "view_section": "Member",
        "description": "multiple subscriptions not deleting, shouldnt happen",
        "swedish": "Något gick fel vid borttagningen av din prenumeration. Kontakta supporten för assistans.",
    },
    {
        "code": "24",
        "view_section": "Member",
        "description": "multiple subscriptions delete, first try fail shouldnt happen",
        "swedish": "Något gick fel vid borttagningen av din prenumeration. Kontakta supporten för assistans.",
    },
    {
        "code": "25",
        "view_section": "Member",
        "description": "single subscription post access no such sub",
        "swedish": "Något gick fel vid laddningen av din prenumeration. Kontakta supporten för assistans.",
    },
    {
        "code": "26",
        "view_section": "Member",
        "description": "single subscription save, sub id doesnt exist",
        "swedish": "Vi kan inte hitta din prenumeration. Om detta fel fortsätter inträffa, var god Kontakta supporten för assistans.",
    },
    {
        "code": "27",
        "view_section": "Member",
        "description": "single subscription save form not valid",
        "swedish": "Vi saknar information i något obligatoriskt fält. Var vänlig fyll i hela formuläret.",
    },
    {
        "code": "28",
        "view_section": "Member",
        "description": "single subscription deactivate, sub doesnt exist",
        "swedish": "Något gick fel vid avaktiveringen av denna prenumeration. Var god kontakta supporten för assistans.",
    },
    {
        "code": "29",
        "view_section": "Member",
        "description": "single subscription not save or deactivate chosen, but still post, something wrong",
        "swedish": "Något gick fel vid avaktiveringen av denna prenumeration. Var god kontakta supporten för assistans.",
    },
    {
        "code": "30",
        "view_section": "Member",
        "description": "Cookie settings access",
        "swedish": "Något gick fel vid laddningen av dina kakinställningar. Var god kontakta support för hjälp.",
    },
    {
        "code": "31",
        "view_section": "Member",
        "description": "Cookie settings save, object does not exist fail",
        "swedish": "Något gick fel vid sparandet av dina inställningar. Var god kontakta support för hjälp.",
    },
    {
        "code": "32",
        "view_section": "Member",
        "description": "Generic support form access",
        "swedish": "Något gick fel vid laddningen av kontaktformuläret. Var god kontakta supporten via email på:",
    },
    {
        "code": "33",
        "view_section": "Member",
        "description": "Generic support form save subject error",
        "swedish": "Ämnesraden innehåller icke tillåtna tecken. Tillåtna tecken är stora och små bokstäver, siffror, komma, punkt, utropstecken och frågetecken endast.",
    },
    {
        "code": "34",
        "view_section": "Member",
        "description": "Generic support form post error",
        "swedish": "Något gick fel vid skickandet av kontaktformuläret. Var god kontakta supporten via email på:",
    },
    {
        "code": "35",
        "view_section": "Moderator",
        "description": "Overview access",
        "swedish": "Något gick fel vid laddningen av överblicken. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "36",
        "view_section": "Moderator",
        "description": "Overview paging error for specific page subscriptions",
        "swedish": "Något är fel bläddringsfunktionen på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "37",
        "view_section": "Moderator",
        "description": "Overview paging error for specific page orders",
        "swedish": "Något är fel bläddringsfunktionen på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "38",
        "view_section": "Moderator",
        "description": "Overview next order page",
        "swedish": "Något är fel bläddringsfunktionen på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "39",
        "view_section": "Moderator",
        "description": "Overview previous order page",
        "swedish": "Något är fel bläddringsfunktionen på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "40",
        "view_section": "Moderator",
        "description": "Overview next support page",
        "swedish": "Något är fel bläddringsfunktionen på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "41",
        "view_section": "Moderator",
        "description": "Overview previous support page",
        "swedish": "Något är fel bläddringsfunktionen på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "42",
        "view_section": "Moderator",
        "description": "overview object does not exist error, post",
        "swedish": "Något gick fel vid bläddringen till nästa sida på överblickssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "43",
        "view_section": "Support",
        "description": "Order search access",
        "swedish": "Något gick fel vid laddningen av orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "44",
        "view_section": "Support",
        "description": "Order search post object does not exist error",
        "swedish": "Något gick fel vid laddningen av orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "45",
        "view_section": "Support",
        "description": "Order search previous page",
        "swedish": "Något är fel bläddringsfunktionen på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "46",
        "view_section": "Support",
        "description": "Order search previous page",
        "swedish": "Något är fel bläddringsfunktionen på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "47",
        "view_section": "Support",
        "description": "Order search next page",
        "swedish": "Något är fel bläddringsfunktionen på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "48",
        "view_section": "Support",
        "description": "Order search specific page number larger than 2",
        "swedish": "Något är fel bläddringsfunktionen på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "49",
        "view_section": "Support",
        "description": "Order search specific page number 2 or 1",
        "swedish": "Något är fel bläddringsfunktionen på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "50",
        "view_section": "Support",
        "description": "User search post that isnt pagination",
        "swedish": "Något är fel på användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "51",
        "view_section": "Support",
        "description": "Order search post object does not exist",
        "swedish": "Något är fel på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "52",
        "view_section": "Support",
        "description": "Specific order view access post",
        "swedish": "Kan inte hitta ordern. Om detta fel fortsätter inträffa. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "53",
        "view_section": "Support",
        "description": "Support view access",
        "swedish": "Något gick fel när vi laddade denna sida. Kontakta IT support för assistans.",
    },
    {
        "code": "54",
        "view_section": "Support",
        "description": "errand view accress",
        "swedish": "Något gick fel när vi laddade denna sida. Kontakta IT support för assistans.",
    },
    {
        "code": "55",
        "view_section": "Support",
        "description": "single user view save userinfo with the id doesnt exist (rebuild this function, needs to setup profile if it doesnt exist)",
        "swedish": "Kan inte ladda användarens information. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "56",
        "view_section": "Support",
        "description": "single user view post object does not exist",
        "swedish": "Kan inte ladda användarens information. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "57",
        "view_section": "Support",
        "description": "company view access",
        "swedish": "Företaget saknas. Något är fel i ändringsformuläret. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "58",
        "view_section": "Support",
        "description": "company view save addressform",
        "swedish": "Det verkar saknas information. Kolla addressinformationen i formuläret. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "59",
        "view_section": "Support",
        "description": "company view save company form",
        "swedish": "Det verkar saknas information. Kolla företagsinformationen i formuläret. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "60",
        "view_section": "Support",
        "description": "company view user doesnt exist in save company",
        "swedish": "Användaren saknas. Något är fel i ändringsformuläret. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "61",
        "view_section": "Support",
        "description": "edit addresses delete company address",
        "swedish": "Denna address är kopplad till kundens företag. Var god ändra addressen för företaget innan du tar bort den.",
    },
    {
        "code": "62",
        "view_section": "Support",
        "description": "edit addresses delete subscription address",
        "swedish": "Denna address är kopplad till minst en kundens prenumerationer. Var god ändra addressen för prenumerationerna innan du tar bort den.",
    },
    {
        "code": "63",
        "view_section": "Support",
        "description": "edit addresses post not delete",
        "swedish": "Kan inte läsa in användarens address. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "64",
        "view_section": "Support",
        "description": "edit addresses post object does not exist",
        "swedish": "Kan inte läsa in användarens address. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "65",
        "view_section": "Support",
        "description": "edit single address get redirect",
        "swedish": "Kan inte läsa in användarens address. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "66",
        "view_section": "Support",
        "description": "edit single address save, address type off",
        "swedish": "Kan inte spara in användarens address. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "67",
        "view_section": "Support",
        "description": "new address get redirect",
        "swedish": "Kan inte läsa in ny adress formuläret. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "68",
        "view_section": "Support",
        "description": "new address save, form invalid",
        "swedish": "Nödvändig information saknas i formuläret. Var god fyll i denna.",
    },
    {
        "code": "69",
        "view_section": "Support",
        "description": "settings post object does not exist",
        "swedish": "Kan inte hitta denna användares inställningar. Om detta fortgår, kontakta IT support.",
    },
    {
        "code": "70",
        "view_section": "Support",
        "description": "multiple subscriptions view get redirect",
        "swedish": "Kan inte läsa in prenumerationerna. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "71",
        "view_section": "Support",
        "description": "multiple subscriptions view delete, sub active no order",
        "swedish": "Prenumerationen var aktiv utan att en kopplad order var funnen. Kolla att det inte finns kvar en order som borde varit kopplad till denna.",
    },
    {
        "code": "72",
        "view_section": "Support",
        "description": "multiple subscriptions view no such subscription",
        "swedish": "Prenumerationen finns inte. Om den fortsätter synas efter omladdning kontakta IT support för hjälp.",
    },
    {
        "code": "73",
        "view_section": "Support",
        "description": "multiple subscriptions view we dont have a user to delete the subscription of",
        "swedish": "Någonting gick fel vid borttagningen av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "74",
        "view_section": "Support",
        "description": "multiple subscriptions view post but not see or delete",
        "swedish": "Någonting gick fel vid borttagningen av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "75",
        "view_section": "Support",
        "description": "multiple subscriptions view post object does not exist error",
        "swedish": "Någonting gick fel vid borttagningen av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "76",
        "view_section": "Support",
        "description": "single subscription get redirect",
        "swedish": "Någonting gick fel vid inläsningen av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "77",
        "view_section": "Support",
        "description": "single subscription access",
        "swedish": "Någonting gick fel vid inläsningen av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "78",
        "view_section": "Support",
        "description": "single subscription save old, object does not exist",
        "swedish": "Någonting gick fel vid sparandet av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "79",
        "view_section": "Support",
        "description": "single subscription not old subscription, cant save",
        "swedish": "Det ser ut som om du försöker skapa en ny prenumeration. Om detta inte är fallet, kontakta IT support för assistans. Om detta är fallet så be användaren skapa prenumerationen då detta inte bör göras av personal.",
    },
    {
        "code": "80",
        "view_section": "Support",
        "description": "single subscription trying to deactivate without a subid",
        "swedish": "Någonting gick fel vid avaktiveringen av denna prenumeration. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "81",
        "view_section": "Support",
        "description": "single subscription post not deactivate, save or see",
        "swedish": "Du verkar ha påträffat ett programmeringsfel på prenumerationssidan. Var god kontakta IT support.",
    },
    {
        "code": "82",
        "view_section": "Support",
        "description": "single subscription post object does not exist",
        "swedish": "Du verkar ha påträffat ett programmeringsfel på prenumerationssidan. Var god kontakta IT support.",
    },
    {
        "code": "83",
        "view_section": "Support",
        "description": "personal profile object does not exist",
        "swedish": "Något gick fel när vi försökte läsa in din profil. Kontakta IT support för assistans.",
    },
    {
        "code": "84",
        "view_section": "Support",
        "description": "personal information change get object does not exist",
        "swedish": "Något gick fel när vi försökte läsa in din information. Kontakta IT support för assistans.",
    },
    {
        "code": "85",
        "view_section": "Support",
        "description": "personal profile post object does not exist",
        "swedish": "Något gick fel när vi försökte spara in din information. Kontakta IT support för assistans.",
    },
    {
        "code": "86",
        "view_section": "Moderator",
        "description": "product handling get object does not exist",
        "swedish": "Något är fel med produkthanteringssidan. Kontakta IT support för assistans.",
    },
    {
        "code": "87",
        "view_section": "Moderator",
        "description": "product handling previous page, page above 2",
        "swedish": "Något är fel med produkthanteringssidans bläddringsfunktion. Kontakta IT support för assistans.",
    },
    {
        "code": "88",
        "view_section": "Support",
        "description": "product handling previous page, 2 0r 1",
        "swedish": "Något är fel med produkthanteringssidans bläddringsfunktion. Kontakta IT support för assistans.",
    },
    {
        "code": "89",
        "view_section": "Moderator",
        "description": "product handling post object does not exist",
        "swedish": "Något är fel med produkthanteringssidan. Kontakta IT support för assistans.",
    },
    {
        "code": "90",
        "view_section": "Moderator",
        "description": "specific product view get redirect",
        "swedish": "Något gick fel när vi försökte läsa in denna produkt. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "91",
        "view_section": "Moderator",
        "description": "specific product view look at",
        "swedish": "Produkten finns inte. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "92",
        "view_section": "Support",
        "description": "single user view get redirect",
        "swedish": "Kan inte hitta användaren. Om detta fortsätter hända, kontakta IT support för assistans.",
    },
    {
        "code": "93",
        "view_section": "Support",
        "description": "company view get redirect",
        "swedish": "Kan inte ladda användarens företagsinformation. Om detta problem fortgår, kontakta IT support för assistans.",
    },
    {
        "code": "94",
        "view_section": "Support",
        "description": "edit addresses get redirect",
        "swedish": "Kan inte läsa in användarens addresser. Om detta problemet fortgår kontakta IT support för assistans.",
    },
    {
        "code": "95",
        "view_section": "Support",
        "description": "settings get redirect",
        "swedish": "Kan inte läsa in denna användare. Om problemet fortgår, kontakta IT supporten för hjälp.",
    },
    {
        "code": "96",
        "view_section": "Moderator",
        "description": "Category Overview get object does not exist",
        "swedish": "Något är fel med kategorisidorna. Kontakta IT support för assistans.",
    },
    {
        "code": "97",
        "view_section": "Moderator",
        "description": "Category Overview search not valid",
        "swedish": "Var god fyll i ett riktigt kategori id.",
    },
    {
        "code": "98",
        "view_section": "Moderator",
        "description": "Category Overview previous page, page above 2, object does not exist",
        "swedish": "Något är fel med kategorisidornas sidbläddringsfunktion. Kontakta IT support för assistans.",
    },
    {
        "code": "99",
        "view_section": "Moderator",
        "description": "Category Overview previous page, page 1 or 2, object does not exist",
        "swedish": "Något är fel med kategorisidornas sidbläddringsfunktion. Kontakta IT support för assistans.",
    },
    {
        "code": "100",
        "view_section": "Moderator",
        "description": "Category Overview post object does not exist",
        "swedish": "Något är fel med kategorisidorna. Kontakta IT support för assistans.",
    },
    {
        "code": "101",
        "view_section": "Moderator",
        "description": "single category save",
        "swedish": "Alla fält är inte i fyllda i formuläret. Var god fyll i dessa innan du sparar.",
    },
    {
        "code": "102",
        "view_section": "Moderator",
        "description": "single category post with incorrect variables",
        "swedish": "Något gick fel när vi försökte läsa in denna kategori. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "103",
        "view_section": "Moderator",
        "description": "product handling search",
        "swedish": "Var god fyll i ett korrekt produkt id.",
    },
    {
        "code": "104",
        "view_section": "Moderator",
        "description": "single category get redirect",
        "swedish": "Något gick fel när vi försökte läsa in denna kategori. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "105",
        "view_section": "Moderator",
        "description": "specific order handling get redirect",
        "swedish": "Kan inte läsa in ordern. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "106",
        "view_section": "Moderator",
        "description": "specific order handling post: look at no such order",
        "swedish": "Kan inte läsa in ordern. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "107",
        "view_section": "Moderator",
        "description": "specific order handling nothing in post keys",
        "swedish": "Något är fel i formuläret på sidan. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "108",
        "view_section": "Moderator",
        "description": "specific order handling order not sent",
        "swedish": "Ordern är inte markerad som skickad. Inga delar är markerade som packade.",
    },
    {
        "code": "109",
        "view_section": "Support",
        "description": "Specific order view access get",
        "swedish": "Kan inte hitta ordern. Om detta fel fortsätter inträffa. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "110",
        "view_section": "Support",
        "description": "Specific order view subscription order subscription missing",
        "swedish": "Kan inte hitta orderns prenumeration. Om detta fel fortsätter inträffa. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "111",
        "view_section": "Support",
        "description": "Specific order view save no such order",
        "swedish": "Kan inte hitta ordern när vi sparar. Om detta fel fortsätter inträffa. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "112",
        "view_section": "Support",
        "description": "Specific order view nothing marked",
        "swedish": "Kan inte hitta något val i formuläret. Om du fyllt i något val och detta ändå händer, kontakta IT supporten.",
    },
    {
        "code": "113",
        "view_section": "Support",
        "description": "Specific order view save order is being packed",
        "swedish": "Ordern packas just nu. Kan inte tas bort eller avbokas just nu. Be kunden returnera ordern.",
    },
    {
        "code": "114",
        "view_section": "Support",
        "description": "Specific order view refund did not mark request",
        "swedish": "Du kan inte återbetala en order utan att markera att återbetalning är begärd. Var god kolla formuläret innan du skicar igen.",
    },
    {
        "code": "115",
        "view_section": "Moderator",
        "description": "Single Freight handling update not valid form",
        "swedish": "Något saknas i formuläret. Var god fyll i det helt innan du sparar igen.",
    },
    {
        "code": "116",
        "view_section": "Moderator",
        "description": "Single Freight handling new not valid form",
        "swedish": "Något saknas i formuläret. Var god fyll i det helt innan du sparar igen.",
    },
    {
        "code": "117",
        "view_section": "Moderator",
        "description": "order handling pagination in search",
        "swedish": "Något är fel med orderhanteringssidornas blädringsfunktion. Kontakta IT support för assistans.",
    },
    {
        "code": "118",
        "view_section": "Support",
        "description": "single subscription trying to deactivate while order is being packed",
        "swedish": "Ordern som är kopplad packas just nu. Meddela detta till kunden och avaktivera efter att ordern skickats.",
    },
    {
        "code": "119",
        "view_section": "Support",
        "description": "Order search post that isnt pagination",
        "swedish": "Något är fel på orderhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "120",
        "view_section": "Support",
        "description": "User search access",
        "swedish": "Något gick fel vid laddningen av användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "121",
        "view_section": "Support",
        "description": "User search previous page",
        "swedish": "Något är fel bläddringsfunktionen på användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "122",
        "view_section": "Support",
        "description": "User search next page",
        "swedish": "Något är fel bläddringsfunktionen på användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "123",
        "view_section": "Support",
        "description": "User search specific page number larger than 2",
        "swedish": "Något är fel bläddringsfunktionen på användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "124",
        "view_section": "Support",
        "description": "User search specific page number 2 or 1",
        "swedish": "Något är fel bläddringsfunktionen på användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "125",
        "view_section": "Support",
        "description": "User search post object does not exist",
        "swedish": "Något är fel på användarhanteringssidan. Var god kontakta IT supporten för assistans.",
    },
    {
        "code": "126",
        "view_section": "Moderator",
        "description": "specific order handling save no such order",
        "swedish": "Kan inte markera ordern som skickad. Kontakta IT support för assistans om problemet fortgår.",
    },
    {
        "code": "127",
        "view_section": "Support",
        "description": "orderItem item does not exist",
        "swedish": "Vi kan inte hitta denna ordervara. Var vänlig kontakta IT support.",
    },
    {
        "code": "128",
        "view_section": "Support",
        "description": "users company has this address",
        "swedish": "Kundens företag är kopplat till denna address. Var god ändra företagsaddressen först innan du försöker ta bort denna.",
    },
    {
        "code": "129",
        "view_section": "Moderator",
        "description": "Single Coupon handling update not valid form",
        "swedish": "Någonting saknas i formuläret. Var god fyll i alla obligatoriska fält.",
    },
    {
        "code": "130",
        "view_section": "Moderator",
        "description": "New save form invalid",
        "swedish": "Någonting saknas i formuläret. Var god fyll i alla obligatoriska fält.",
    },
    {
        "code": "131",
        "view_section": "Member",
        "description": "Change password get redirect",
        "swedish": "Vi kunde inte ladda den här sidan just nu. Om problemet fortgår kontakta supporten för hjälp.",
    },
    {
        "code": "132",
        "view_section": "Member",
        "description": "Change password not see or save",
        "swedish": "Vi kunde inte ladda sidan. Om problemet fortgår kontakta supporten.",
    },
    {
        "code": "133",
        "view_section": "Member",
        "description": "Chancel order access",
        "swedish": "Vi kunde inte ladda sidan. Om problemet fortgår kontakta supporten.",
    },
    {
        "code": "134",
        "view_section": "Member",
        "description": "Return order access",
        "swedish": "Vi kunde inte ladda sidan. Om problemet fortgår kontakta supporten.",
    },
    {
        "code": "135",
        "view_section": "Member",
        "description": "Return item access",
        "swedish": "Vi kunde inte ladda sidan. Om problemet fortgår kontakta supporten.",
    },
    {
        "code": "136",
        "view_section": "Core",
        "description": "Add Coupon View access",
        "swedish": "Vi kunde inte ladda sidan. Om problemet fortgår kontakta supporten.",
    },
    {
        "code": "137",
        "view_section": "Core",
        "description": "Faqs missing from database",
        "swedish": "Det har inträffat ett fel i samband med hämtningen av informationen från databasen. Var god kontakta supporten för hjälp",
    },
]
