infoFile = [
    {
        "code": "1",
        "view_section": "Setup",
        "description": "Account setup form saved.",
        "swedish": "Uppgifter sparade. Du kan uppdatera och lägga till information under din profil.",
    },
    {
        "code": "2",
        "view_section": "Member",
        "description": "Company save",
        "swedish": "Informationen sparad.",
    },
    {
        "code": "3",
        "view_section": "Member",
        "description": "Profile Delete address",
        "swedish": "Address borttagen",
    },
    {
        "code": "4",
        "view_section": "Member",
        "description": "info view save",
        "swedish": "Användarinformationen sparad.",
    },
    {
        "code": "5",
        "view_section": "Member",
        "description": "edit address save",
        "swedish": "Addressen har sparats.",
    },
    {
        "code": "6",
        "view_section": "Member",
        "description": "New address address exists and hasn't been asked to be default",
        "swedish": "Addressen finns redan.",
    },
    {
        "code": "7",
        "view_section": "Member",
        "description": "New address address exists and has been asked to be default",
        "swedish": "Addressen finns redan. Har ändrat förvald address till denna.",
    },
    {
        "code": "8",
        "view_section": "Member",
        "description": "New address asked for both, both exist, default not changed",
        "swedish": "Du har redan denna adress sparad som både leverans och faktura adress sedan tidigare.",
    },
    {
        "code": "9",
        "view_section": "Member",
        "description": "New Address asked for both, both exist, default changed",
        "swedish": "Du har redan denna adress sparad som faktura och leveransadress. Har dock ändrat förvalt till dessa.",
    },
    {
        "code": "10",
        "view_section": "Member",
        "description": "New Address saved",
        "swedish": "Addressen har sparats.",
    },
    {
        "code": "11",
        "view_section": "Member",
        "description": "subscriptions delete both sub and order",
        "swedish": "Premunationen och motsvarande order borttagen.",
    },
    {
        "code": "12",
        "view_section": "Member",
        "description": "subscriptions delete sub",
        "swedish": "Premunation borttagen.",
    },
    {
        "code": "13",
        "view_section": "Member",
        "description": "single subscription save",
        "swedish": "Premunationen sparad och aktiverad.",
    },
    {
        "code": "14",
        "view_section": "Member",
        "description": "single subscription already deactivated",
        "swedish": "Premunation var redan avaktiverad.",
    },
    {
        "code": "15",
        "view_section": "Member",
        "description": "Single subscription deactivate",
        "swedish": "Prenumeration avaktiverad.",
    },
    {
        "code": "16",
        "view_section": "Member",
        "description": "Single subscription deactivate no order connected, this should be reported to IT not the user",
        "swedish": "Prenumeration avaktiverad",
    },
    {
        "code": "17",
        "view_section": "Member",
        "description": "Settings saved",
        "swedish": "Dina inställningar har sparats.",
    },
    {
        "code": "18",
        "view_section": "Member",
        "description": "Generic contact form sent",
        "swedish": "Ärendet skickat. En kopia har skickats till din angivna emailadress.",
    },
    {
        "code": "19",
        "view_section": "Support",
        "description": "Order search search order",
        "swedish": "Ordern finns inte",
    },
    {
        "code": "20",
        "view_section": "Support",
        "description": "Order search search user",
        "swedish": "Användaren finns inte",
    },
    {
        "code": "21",
        "view_section": "Support",
        "description": "User search paging User does not exist.",
        "swedish": "Användaren finns inte.",
    },
    {
        "code": "22",
        "view_section": "Support",
        "description": "User search search",
        "swedish": "Användaren finns inte.",
    },
    {
        "code": "23",
        "view_section": "Support",
        "description": "single user view save",
        "swedish": "Informationen sparad.",
    },
    {
        "code": "24",
        "view_section": "Support",
        "description": "single user view form invalid",
        "swedish": "Information saknas eller är av felaktigt format i formuläret.",
    },
    {
        "code": "25",
        "view_section": "Support",
        "description": "company view save",
        "swedish": "Företagsinformationen updaterad och sparad.",
    },
    {
        "code": "26",
        "view_section": "Support",
        "description": "edit addresses delete",
        "swedish": "Address borttagen.",
    },
    {
        "code": "27",
        "view_section": "Support",
        "description": "edit single address save",
        "swedish": "Addressen har sparats.",
    },
    {
        "code": "28",
        "view_section": "Support",
        "description": "edit single address form invalid",
        "swedish": "Någonting saknas i formuläret. Var god fyll i alla obligatoriska fält.",
    },
    {
        "code": "29",
        "view_section": "Support",
        "description": "new address address exist but hasnt asked for default",
        "swedish": "Denna address finns redan sparad.",
    },
    {
        "code": "30",
        "view_section": "Support",
        "description": "new address address exist, has asked for default",
        "swedish": "Denna address finns redan sparad. Har ändrat förvald address till denna.",
    },
    {
        "code": "31",
        "view_section": "Support",
        "description": "new address save",
        "swedish": "Addressen har sparats.",
    },
    {
        "code": "32",
        "view_section": "Support",
        "description": "multiple subscriptions delete",
        "swedish": "Prenumerationen och tillhörande order borttagen.",
    },
    {
        "code": "33",
        "view_section": "Support",
        "description": "multiple subscriptions no delete",
        "swedish": "Prenumerationen togs inte bort.",
    },
    {
        "code": "34",
        "view_section": "Support",
        "description": "multiple subscriptions delete",
        "swedish": "Prenumerationen borttagen.",
    },
    {
        "code": "35",
        "view_section": "Support",
        "description": "single subscription already deactivated",
        "swedish": "Prenumerationen är redan avaktiverad.",
    },
    {
        "code": "36",
        "view_section": "Support",
        "description": "single subscription deactivate",
        "swedish": "Prenumerationen avaktiverad.",
    },
    {
        "code": "37",
        "view_section": "Support",
        "description": "single subscription deactivate but no order, this should flag for IT support",
        "swedish": "Prenumerationen avaktiverad.",
    },
    {
        "code": "38",
        "view_section": "Support",
        "description": "personal information change save, over old save",
        "swedish": "Användar information sparad.",
    },
    {
        "code": "39",
        "view_section": "Support",
        "description": "personal information change save, new save",
        "swedish": "Användar information sparad.",
    },
    {
        "code": "40",
        "view_section": "Support",
        "description": "personal information change form invalid",
        "swedish": "Nödvändig information saknas i formuläret.",
    },
    {
        "code": "41",
        "view_section": "Moderator",
        "description": "product handling search, paging",
        "swedish": "Produkten saknas.",
    },
    {
        "code": "42",
        "view_section": "Moderator",
        "description": "product handling search",
        "swedish": "Produkten saknas.",
    },
    {
        "code": "43",
        "view_section": "Moderator",
        "description": "single product save",
        "swedish": "Produkten sparad.",
    },
    {
        "code": "44",
        "view_section": "Moderator",
        "description": "category handling search, paging",
        "swedish": "Kategorin saknas.",
    },
    {
        "code": "45",
        "view_section": "Moderator",
        "description": "category handling search",
        "swedish": "Kategorin saknas.",
    },
    {
        "code": "46",
        "view_section": "Moderator",
        "description": "single category save",
        "swedish": "Kategorin Sparad.",
    },
    {
        "code": "47",
        "view_section": "Moderator",
        "description": "category handling delete",
        "swedish": "Kategorin borttagen.",
    },
    {
        "code": "48",
        "view_section": "Moderator",
        "description": "product handling delete",
        "swedish": "Produkt borttagen.",
    },
    {
        "code": "49",
        "view_section": "Moderator",
        "description": "orderhandling display",
        "swedish": "Det finns inga vanliga ordrar för utskick.",
    },
    {
        "code": "50",
        "view_section": "Moderator",
        "description": "orderhandling display subscription orders",
        "swedish": "Det finns inga prenumerations ordrar för utskick.",
    },
    {
        "code": "51",
        "view_section": "Moderator",
        "description": "single order handling sent",
        "swedish": "Ordern markerad som skickad.",
    },
    {
        "code": "52",
        "view_section": "Support",
        "description": "Specific order saved refund requested",
        "swedish": "Full återbetalning begärd",
    },
    {
        "code": "53",
        "view_section": "Support",
        "description": "Specific order save refund granted",
        "swedish": "Återbetalning beviljad",
    },
    {
        "code": "54",
        "view_section": "Support",
        "description": "Specific order saved induvidual items",
        "swedish": "Varor flaggade för retur:",
    },
    {
        "code": "55",
        "view_section": "Support",
        "description": "Specific order saved induvidual items refund on following items",
        "swedish": "Återbetalning beviljad på följande varor:",
    },
    {
        "code": "56",
        "view_section": "Support",
        "description": "Specific order saved full return flag",
        "swedish": "Order flaggad för retur",
    },
    {
        "code": "57",
        "view_section": "Support",
        "description": "Specific order saved full return flag unflag",
        "swedish": "Order avflaggad för retur",
    },
    {
        "code": "58",
        "view_section": "Support",
        "description": "Specific order saved full return",
        "swedish": "Hela ordern har returnerats",
    },
    {
        "code": "59",
        "view_section": "Support",
        "description": "Specific order saved full return unflag",
        "swedish": "Avmarkering av att hela ordern skulle ha returnerats.",
    },
    {
        "code": "60",
        "view_section": "Support",
        "description": "Specific order save refund requested cancel",
        "swedish": "Avanmäld full återbetalning begärd",
    },
    {
        "code": "61",
        "view_section": "Support",
        "description": "Specific order save refund granted cancel",
        "swedish": "Återbetalning avbruten.",
    },
    {
        "code": "62",
        "view_section": "Support",
        "description": "Specific order saved induvidual items Item unflagged for return:",
        "swedish": "Varor avflaggade för retur:",
    },
    {
        "code": "63",
        "view_section": "Support",
        "description": "Specific order saved induvidual items Item refund canceled:",
        "swedish": "Återbetalning avbruten för följande varor:",
    },
    {
        "code": "64",
        "view_section": "Support",
        "description": "orderItem return flag",
        "swedish": "har flaggats för retur",
    },
    {
        "code": "65",
        "view_section": "Support",
        "description": "orderItem unreturn flag",
        "swedish": "har avflaggats för retur",
    },
    {
        "code": "66",
        "view_section": "Support",
        "description": "orderItem returned",
        "swedish": "har returnerats",
    },
    {
        "code": "67",
        "view_section": "Support",
        "description": "orderItem unreturn",
        "swedish": "har inte returnerats",
    },
    {
        "code": "68",
        "view_section": "Support",
        "description": "orderItem payback request",
        "swedish": "Återbetalning begärd för följande varor:",
    },
    {
        "code": "69",
        "view_section": "Support",
        "description": "orderItem payback request canceled",
        "swedish": "Återbetalningsbegäran avbruten för följande varor:",
    },
    {
        "code": "70",
        "view_section": "Support",
        "description": "orderItem payback",
        "swedish": "Återbetalning beviljad för följance varor:",
    },
    {
        "code": "71",
        "view_section": "Support",
        "description": "orderItems payback canceled",
        "swedish": "Återbetalning avbruten för följande varor:",
    },
    {
        "code": "72",
        "view_section": "Support",
        "description": "orderItem saved",
        "swedish": "sparad",
    },
    {
        "code": "74",
        "view_section": "Moderator",
        "description": "Freight handling Updated",
        "swedish": "Fraktalternativ har updaterats.",
    },
    {
        "code": "75",
        "view_section": "Moderator",
        "description": "Freight handling new",
        "swedish": "Fraktalternativ har skapats.",
    },
    {
        "code": "76",
        "view_section": "Moderator",
        "description": "Freight handling delete",
        "swedish": "Fraktalternativ borttagen.",
    },
    {
        "code": "77",
        "view_section": "Support",
        "description": "single subscription save",
        "swedish": "Prenumerationen sparad och aktiverad.",
    },
    {
        "code": "78",
        "view_section": "Moderator",
        "description": "Code handling delete",
        "swedish": "Kuppong borttagen.",
    },
    {
        "code": "79",
        "view_section": "Moderator",
        "description": "Couponhandling Updated",
        "swedish": "Kuppong uppdaterad.",
    },
    {
        "code": "80",
        "view_section": "Moderator",
        "description": "Coupon save",
        "swedish": "Kuppong sparad.",
    },
    {
        "code": "81",
        "view_section": "Member",
        "description": "change password save",
        "swedish": "Lösenordet sparat.",
    },
    {
        "code": "82",
        "view_section": "Member",
        "description": "change password wrong password",
        "swedish": "Det gamla lösenordet är felaktigt. Om du glömt ditt lösenord gå till:",
    },
]

# no 73 add here first
