# Generated by Django 2.2.6 on 2020-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fake_class',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[{'key': 'B', 'name': 'Fakturaaddress'}, {'key': 'S', 'name': 'Leveransaddress'}], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media_root/'),
        ),
    ]
