# Generated by Django 2.2.6 on 2020-02-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200212_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(default='address'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slug',
            field=models.SlugField(default='company'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='item'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='order'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='slug',
            field=models.SlugField(default='support'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(default='userinfo'),
        ),
    ]
