# Generated by Django 2.2.6 on 2020-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200212_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='post_town',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
