# Generated by Django 2.2.6 on 2020-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200313_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='swedish',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='informationmessages',
            name='swedish',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='swedish',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='warningmessages',
            name='swedish',
            field=models.TextField(null=True),
        ),
    ]
