# Generated by Django 2.2.7 on 2019-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'Tobaksfritt Snus'), ('CS', 'Classikt Snus'), ('OT', 'Annat')], max_length=2),
        ),
    ]
