# Generated by Django 2.2.6 on 2020-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200313_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='code',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='informationmessages',
            name='code',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='code',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='warningmessages',
            name='code',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
