# Generated by Django 2.2.6 on 2020-02-16 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_post_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@test.se', max_length=254)),
                ('subject', models.CharField(default='subject', max_length=200)),
                ('message', models.TextField(default='Text')),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(default='support')),
            ],
        ),
    ]
