# Generated by Django 2.2.6 on 2020-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200313_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormessages',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='errormessages',
            name='info_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='informationmessages',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='informationmessages',
            name='info_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='info_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='warningmessages',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='warningmessages',
            name='info_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
