# Generated by Django 2.2.6 on 2020-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscription_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
