# Generated by Django 2.2.7 on 2019-12-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191204_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'Tobaksfritt Snus'), ('CS', 'Classikt Snus'), ('TB', 'Tillbehör')], max_length=2),
        ),
    ]
