# Generated by Django 2.2.7 on 2019-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191204_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'Tobaksfritt Snus'), ('KS', 'Klassikt Snus'), ('TB', 'Tillbehör')], max_length=2),
        ),
    ]
