# Generated by Django 2.2.6 on 2020-02-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200217_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookies',
            name='onOff',
        ),
    ]
