# Generated by Django 2.2.6 on 2020-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200313_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(default='coupon'),
        ),
    ]
