# Generated by Django 2.2.6 on 2020-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_flag',
            field=models.BooleanField(default=False),
        ),
    ]
