# Generated by Django 2.2.6 on 2020-02-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cookies_onoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookies',
            name='directed_ads',
        ),
        migrations.RemoveField(
            model_name='cookies',
            name='measurement',
        ),
    ]
