# Generated by Django 2.2.6 on 2020-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200323_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024, null=True)),
                ('description', models.TextField(null=True)),
                ('swedish_subject', models.TextField(null=True)),
                ('swedish_content', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='freight',
            name='test',
        ),
    ]
