# Generated by Django 2.2.6 on 2020-03-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200311_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_flag',
            field=models.BooleanField(default=False),
        ),
    ]
