# Generated by Django 2.2.6 on 2020-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200217_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='addapted_adds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='functional',
            field=models.BooleanField(default=True),
        ),
    ]
