# Generated by Django 2.2.6 on 2020-01-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200122_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='UserSettings',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
