# Generated by Django 2.2.6 on 2020-01-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200122_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportthread',
            name='responce',
        ),
        migrations.AddField(
            model_name='supportresponces',
            name='ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.SupportThread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportthread',
            name='last_responce',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
