# Generated by Django 2.2.6 on 2020-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_refund_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[{'key': 'S', 'name': 'Stripe'}, {'key': 'P', 'name': 'Paypal'}, {'key': 'I', 'name': 'Invoice'}], default='S', max_length=1),
        ),
    ]
