# Generated by Django 2.2.6 on 2020-03-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200323_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='code',
        ),
    ]
