# Generated by Django 2.2.6 on 2020-01-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200122_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookies',
            old_name='tracking',
            new_name='onOff',
        ),
    ]
