# Generated by Django 2.2.6 on 2020-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200122_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
