# Generated by Django 2.2.6 on 2020-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
