# Generated by Django 2.2.6 on 2020-03-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_freight_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freight_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Freight'),
        ),
    ]
