# Generated by Django 2.2.6 on 2020-04-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200423_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTypeChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textType', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='code',
        ),
        migrations.AlterField(
            model_name='textfield',
            name='description',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfield',
            name='textType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TextTypeChoices'),
        ),
    ]
