# Generated by Django 2.2.6 on 2020-01-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200122_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportthread',
            name='message',
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_order', to='core.Order'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(default='unumber'),
        ),
    ]
