# Generated by Django 2.2.6 on 2020-04-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200428_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
