# Generated by Django 2.2.6 on 2020-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200312_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(default='Percent', max_length=20),
        ),
    ]
