# Generated by Django 2.2.6 on 2020-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200428_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='short_hand',
            field=models.CharField(default='fixthis', max_length=20),
        ),
    ]
