# Generated by Django 2.2.6 on 2020-09-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_textfield_short_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionItem',
        ),
    ]
