# Generated by Django 2.2.6 on 2020-01-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200130_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='items',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='ref',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.Subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
