# Generated by Django 2.2.6 on 2020-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200929_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=3)),
            ],
        ),
    ]
