# Generated by Django 2.2.6 on 2020-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200131_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='number_of_items',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
