# Generated by Django 2.2.6 on 2020-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymenttypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldFreight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='freight',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
