# Generated by Django 2.2.6 on 2020-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teamstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstaff',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
