# Generated by Django 2.2.6 on 2020-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_orderitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='sub_out_date',
        ),
    ]
