# Generated by Django 2.2.6 on 2020-02-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200208_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_order',
            field=models.BooleanField(default=False),
        ),
    ]
