# Generated by Django 2.2.6 on 2020-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_subscription_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='being_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='freight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
