# Generated by Django 2.2.6 on 2020-10-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201019_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_handled',
            field=models.BooleanField(default=False),
        ),
    ]
