# Generated by Django 2.2.6 on 2020-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201027_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='removed_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='removed_from_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='removed_from_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
