# Generated by Django 2.2.6 on 2020-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201109_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='removed_from_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
